module.exports = [
    {
        id: 1,
        nazev: "iPhone X",
        popis: "Lepší než android",
        cena: 50000,
    },
    {
        id: 2,
        nazev: "iPhone XS",
        popis: "Dvakrát lepší",
        cena: 60000,
    },
    {
        id: 3,
        nazev: "iPhone 13",
        popis: "Hodně dobrej",
        cena: 70000,
    },
    {
        id: 4,
        nazev: "iPhone 12",
        popis: "Skvělí model",
        cena: 80000,
    },
    {
        id: 5,
        nazev: "iPhone 8",
        popis: "Veterán",
        cena: 50000,
    },
    {
        id: 6,
        nazev: "iPhone 4",
        popis: "Velký veterán",
        cena: 40000,
    },
    {
        id: 7,
        nazev: "iPhone 7",
        popis: "Kvalita",
        cena: 60000,
    },
    {
        id: 8,
        nazev: "iPad",
        popis: "kvalitní ipad",
        cena: 60000,
    },
    {
        id: 9,
        nazev: "iPod",
        popis: "kvalitní ipod",
        cena: 70000,
    },
    {
        id: 10,
        nazev: "MacBook",
        popis: "kvalitní mac",
        cena: 80000,
    },
    {
        id: 11,
        nazev: "MacBook Pro",
        popis: "kvalitní macpro",
        cena: 90000,
    },
    {
        id: 12,
        nazev: "MacBook Air",
        popis: "kvalitní macair",
        cena: 100000,
    },
    {
        id: 13,
        nazev: "MacBook classic",
        popis: "kvalitní macclassic",
        cena: 110000,
    },
    {
        id: 14,
        nazev: "Apple TV",
        popis: "kvalitní tv",
        cena: 70000,
    },
    {
        id: 15,
        nazev: "iPhone 6",
        popis: "kvalitní iPhone",
        cena: 50000,
    },
    {
        id: 16,
        nazev: "iPhone 5s",
        popis: "kvalitní iPhone 5s",
        cena: 87000,
    },
    {
        id: 17,
        nazev: "iPhone 7s",
        popis: "kvalitní iPhone 7s",
        cena: 67000,
    },
    {
        id: 18,
        nazev: "iPhone Xr",
        popis: "kvalitní iPhone Xr",
        cena: 97000,
    },
    {
        id: 19,
        nazev: "iPhone 12 PRO",
        popis: "kvalitní iPhone 12 PRO",
        cena: 98000,
    },
    {
        id: 20,
        nazev: "iPhone 13 PRO",
        popis: "kvalitní iPhone 13 PRO",
        cena: 120000,
    },

]