import Head from 'next/head'
import Image from 'next/image'
import produkty from '../resources/produkty';
import Produkt from '../komponenty/Produkt';

export default function Home() {

  console.log(produkty);
  return (
    <>
      <Head>
        <title>Hlavní stránka-iStore</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="produkty container">{produkty.map((produkt, i) => <Produkt produkt={produkt} key={i} />)}</div>




    </>
  )
}
